### ISSUE TITLE
Make all errors out.

### ISSUE THREAD

**Issue by TheCryptek** [lrvick/airgap#1]
So after cloning the repo and attempting to run the make all command I get the error below

```
rm -rf dist
rm -rf .packer/build
packer build --parallel=false packer/build.json
/bin/bash: packer: command not found
Makefile:14: recipe for target 'all' failed
make: *** [all] Error 127
```

**Comment by daveloyall** [comment]
`apt-get install packer`

**Comment by daveloyall** [comment]
Tho, see #2.  According to https://packer.io, the latest version is 1.0.0.

**Comment by TheCryptek** [comment]
@daveloyall Thank you.

**Comment by TheCryptek** [comment]
@lrvick You can close this issue.
