### ISSUE TITLE
Packer fails with `unknown configuration key: format`

### ISSUE THREAD

**Issue by daveloyall** [lrvick/airgap#2]
sebboh⬢boxfactory:~/src/airgap$ make
    rm -rf dist
    rm -rf .packer/build
    sebboh⬢boxfactory:~/src/airgap$ make all
    rm -rf dist
    rm -rf .packer/build
    packer build --parallel=false packer/build.json
    qemu output will be in this color.
    
    1 error occurred:
    
    * unknown configuration key: "format"
    Makefile:14: recipe for target 'all' failed
    make: *** [all] Error 1

hm!

    sebboh⬢boxfactory:~/src/airgap$ packer --version
    0.10.2

**Comment by daveloyall** [comment]
$ wget https://releases.hashicorp.com/packer/1.0.0/packer_1.0.0_linux_amd64.zip
    $ unzip packer*.zip -d ~/bin
    $ ca ~/src/airgap && make all

**Comment by TheCryptek** [comment]
For those using kali or parrot security os to do this
```
$ wget https://releases.hashicorp.com/packer/1.0.0/packer_1.0.0_linux_amd64.zip
$ sudo unzip packer*.zip /usr/bin
$ packer --version
1.0.0
$ cd ~/src/airgap && make all
```
[Credit goes to @daveloyall line 2 just needed edited for these niche distros]

**Comment by daveloyall** [comment]
I think your line 2 should have a `-d` in it.

Meanwhile you may find it useful to [add a `~/bin` directory](https://askubuntu.com/questions/402353/how-to-add-home-username-bin-to-path) to any user account (or root).

**Comment by TheCryptek** [comment]
@daveloyall thank you for catching the missing "-d"
